### ISSUE TITLE
Crashes on Windows

### ISSUE THREAD

**Issue by shujaatak** [nemediano/QtOpenGLTemplate#2]
QtOpenGLTemplate crashes each time I run it. Tested with both MSVC and MINGW.

```
02:50:25: Starting C:\Qt_Sandbox\QtOpenGLTemplate\build-MyGLWidget-Desktop_Qt_5_13_2_MSVC2017_64bit-Release\release\MyGLWidget.exe ...
QObject::connect: No such signal BaseOGLWidget::toggleFullScreen()
02:50:31: The program has unexpectedly finished.
02:50:31: The process was ended forcefully.
02:50:31: C:/Qt_Sandbox/QtOpenGLTemplate/build-MyGLWidget-Desktop_Qt_5_13_2_MSVC2017_64bit-Release/release/MyGLWidget.exe crashed.
```

**Comment by shujaatak** [comment]
No error is shown in console.

**Comment by nemediano** [comment]
Forgot to remove legacy code and that was causing it.
Funny, that in Linux just ignored the signal and continue (That is why I did not see it)
Can you test it again and let me know if it works now? (I do not have a Windows environment to test)

**Comment by shujaatak** [comment]
Thank you so much, works perfectly!
