### ISSUE TITLE
 about model load 

### ISSUE THREAD

**Issue by KAL-AL** [nemediano/QtOpenGLTemplate#3]
Thank you very much for your work
Can I load files ply directly？
I'm not sure the template will work in my environment right now 。
I have compiled your template- code 。
The operation effect is as follows
![image](https://user-images.githubusercontent.com/64250862/92361535-1662a600-f121-11ea-8c12-85e4f67c26b4.png)
![image](https://user-images.githubusercontent.com/64250862/92361574-25495880-f121-11ea-8404-4bb5ea6da412.png)

We don't have a separate graphics card in our environment

**Comment by nemediano** [comment]
Hi in principle you should be able to load a *.ply file, whitout any problem. This is not dependent on the template but rather in the version of assimp you are linking against. And I believe the suppport for *.ply in assimp has been around for a few years now.
The error shown in your code is due, your dirver being too new and refusing to use old syntax in GLSL, you can change all the texture2D function in the fragment shader of the template to use the more modern texture function.

**Comment by KAL-AL** [comment]
hi Thank you very much for your reply！
I have compiled your template use vs2019 ，There are no error messages。
But running this program will only show a window, I guarantee that the model path is correct。
This is a screenshot of the program running
![image](https://user-images.githubusercontent.com/64250862/92440814-a5ce8e80-f1df-11ea-9222-c0ccff42665a.png)
This is the model obj file
![image](https://user-images.githubusercontent.com/64250862/92441132-3b6a1e00-f1e0-11ea-8041-9069399c8bf5.png)
Thank you very much.

**Comment by nemediano** [comment]
I believe he template it is working as expected and you do not see any visual output because your model does not define an specular and a diffuse texture. You can try to change the fragment shader accordingly to eighter use a base color or use any other texture in accordance. Look into the file MyGLWindow/meshload.cpp lines 186 - 207 to start making adjustments

**Comment by nemediano** [comment]
It was user misunderstanding that the template is not a model viewer. It could be the basis to create one, but you will need to code the rendering of your particular model. That is why is a template an not a complete product.
